# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ca1JhFAUHXUuyzNIKX3NP0P3cQZCOYrX

# **Line Plot**
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
from matplotlib import pyplot as plt
plt.plot([1,2,3,4,5],[5,99,3,2,1])        #Values
plt.show()                                #To view the Line Plot

plt.plot([1,2,3,4,5],[4,2,1,3,6])
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
from matplotlib import pyplot as plt
import numpy as np
x = np.linspace(0,10,10)
y = np.linspace(0,10,10)
plt.figure(figsize=(3,3),num=1)   #To specify the size of the Graphical Figure
plt.plot(x,y,marker = 'o')        #To mark the line plots points with a circle
plt.title('First Line Plot')      #For giving a title to the Graph
plt.xlabel('X axis')              #Naming the Xaxis
plt.ylabel('Y axis')              #Naming the Yaxis
plt.show()

plt.plot(x,y,marker = 'o')
plt.title('Second Plot')
plt.savefig('ThirdPlot')          #To save the Graphical Figure
plt.close()                       #Used to Save the Graphical figure without displaying it

"""**Passing a single array to Plot Function**"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
from matplotlib import pyplot as plt
import numpy as np
plt.plot([50,100,150,200,250],marker = 'o')
plt.show()

plt.plot(x,y)
plt.plot(x,x**2)
plt.plot(x,x**3)
plt.show()

"""**Line Properties**"""

plt.plot(x,y,color='r',marker='o',linewidth=2,linestyle='--',alpha=0.5,label='line1')
plt.plot(x,x**2,color='#1700BE',marker='D',linewidth=2,alpha=0.5,label='line2')
plt.legend()   #For a box around labels given
plt.show()

plt.plot(x,y,color='r',marker='o',linewidth=2,linestyle='--',alpha=0.5,label='line1')
plt.plot(x,x**2,color='#1700BE',marker='D',linewidth=2,alpha=0.5,label='line2')
plt.legend()                                #For a box around labels given
plt.xticks([0,2,4,6,8,10,12])               #Customizing plot elements
plt.grid()                                  #Grid lines for better understanding  
plt.show()

plt.style.use('ggplot')
plt.plot(x,y,color='r',marker='o',linewidth=2,linestyle='--',alpha=0.5,label='line1')
plt.plot(x,x**2,color='#1700BE',marker='D',linewidth=2,alpha=0.5,label='line2')
plt.legend()                                #For a box around labels given                         
plt.show()

plt.style.use('seaborn')
plt.plot(x,y,color='r',marker='o',linewidth=2,linestyle='--',alpha=0.5,label='line1')
plt.plot(x,x**2,color='#1700BE',marker='D',linewidth=2,alpha=0.5,label='line2')
plt.legend()                                #For a box around labels given                           
plt.show()

plt.style.use('fivethirtyeight')
plt.plot(x,y,color='r',marker='o',linewidth=2,linestyle='--',alpha=0.5,label='line1')
plt.plot(x,x**2,color='#1700BE',marker='D',linewidth=2,alpha=0.5,label='line2')
plt.legend()                                #For a box around labels given                          
plt.show()

plt.style.use('classic')
plt.plot(x,y,color='r',marker='o',linewidth=2,linestyle='--',alpha=0.5,label='line1')
plt.plot(x,x**2,color='#1700BE',marker='D',linewidth=2,alpha=0.5,label='line2')
plt.legend()                                #For a box around labels given                          
plt.show()

plt.style.available

from matplotlib import pyplot as plt
plt.style.use("ggplot")

plt.figure(figsize=(10,5),num=1)

year_x = [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

# Median Developer Salaries by Age
c_dev_y = [25496, 42000, 46123, 49550, 50000,
         59000, 63016, 64028, 68500, 60008, 70002]

# Median Python Developer Salaries by Age
py_dev_y = [20000, 40000, 50850, 57287, 63016,
            65998, 70003, 70000, 71496, 75370, 82340]

# Median Java Developer Salaries by Age
j_dev_y = [32810, 43515, 46823, 49293, 53437,
            56373, 62375, 66674, 66000, 68746, 74583]

# Median Ruby Developer Salaries by Age
f_dev_y = [30810, 22515, 19823, 40293, 43437,
            30000, 10375, 0, 0, 0, 0]


plt.plot(year_x, c_dev_y, color="#542457", linestyle="--", marker="o", linewidth=1, label="C Developers")
plt.plot(year_x, py_dev_y, color="#962237",  linestyle="--", marker="v", linewidth=1, label="Python Developers")
plt.plot(year_x, j_dev_y, color="#22968F",  linestyle="--", marker="s", linewidth=1, label="Java Developers")
plt.plot(year_x, f_dev_y, color="green",  linestyle="--", marker="p", linewidth=1, label="Fortran Developers")

plt.xticks(year_x,rotation = 45)
plt.xlabel("Year")
plt.ylabel("Pay - IND")
plt.title("Median Salary For Different Programming Language Developers")
plt.grid(True)
plt.legend()
plt.show()